# Generated by Django 5.0.4 on 2024-07-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='pincode',
            new_name='zipcode',
        ),
    ]
